### ISSUE TITLE
List of unmerged madler/zlib pull requests

### ISSUE THREAD

**Issue by timofonic** [Dead2/zlib-ng#118]
Hello.

Sorry for the long list. I would like to know if the following issues in madler's zlib are fixed in your fork. Of course, you may simply ignore the irrelevant ones (sorry, I'm not sure what are or not).

Thanks in advance.

https://github.com/madler/zlib/pull/295
https://github.com/madler/zlib/pull/292
https://github.com/madler/zlib/pull/291
https://github.com/madler/zlib/pull/285
https://github.com/madler/zlib/pull/284
https://github.com/madler/zlib/pull/283
https://github.com/madler/zlib/pull/282
https://github.com/madler/zlib/pull/281
https://github.com/madler/zlib/pull/279
https://github.com/madler/zlib/pull/278
https://github.com/madler/zlib/pull/277
https://github.com/madler/zlib/pull/271
https://github.com/madler/zlib/pull/270 (msvc15, msvc17)
https://github.com/madler/zlib/pull/269
https://github.com/madler/zlib/pull/267
https://github.com/madler/zlib/pull/265
https://github.com/madler/zlib/pull/264
https://github.com/madler/zlib/pull/263
https://github.com/madler/zlib/pull/261
https://github.com/madler/zlib/pull/260
https://github.com/madler/zlib/pull/257
https://github.com/madler/zlib/pull/256
https://github.com/madler/zlib/pull/255
https://github.com/madler/zlib/pull/251
https://github.com/madler/zlib/pull/248
https://github.com/madler/zlib/pull/243
https://github.com/madler/zlib/pull/242
https://github.com/madler/zlib/pull/240
https://github.com/madler/zlib/pull/239
https://github.com/madler/zlib/pull/237
https://github.com/madler/zlib/pull/234
https://github.com/madler/zlib/pull/233
https://github.com/madler/zlib/pull/230
https://github.com/madler/zlib/pull/229
https://github.com/madler/zlib/pull/228
https://github.com/madler/zlib/pull/226
https://github.com/madler/zlib/pull/225
https://github.com/madler/zlib/pull/224
https://github.com/madler/zlib/pull/220
https://github.com/madler/zlib/pull/219
https://github.com/madler/zlib/pull/211
https://github.com/madler/zlib/pull/210
https://github.com/madler/zlib/pull/209
https://github.com/madler/zlib/pull/208
https://github.com/madler/zlib/pull/207
https://github.com/madler/zlib/pull/201
https://github.com/madler/zlib/pull/197
https://github.com/madler/zlib/pull/196
https://github.com/madler/zlib/pull/195
https://github.com/madler/zlib/pull/194
https://github.com/madler/zlib/pull/193
https://github.com/madler/zlib/pull/186
https://github.com/madler/zlib/pull/184 (applied, but unreplied message)
https://github.com/madler/zlib/pull/182
https://github.com/madler/zlib/pull/181 (msvc15)
https://github.com/madler/zlib/pull/179
https://github.com/madler/zlib/pull/178
https://github.com/madler/zlib/pull/177
https://github.com/madler/zlib/pull/176 (merged? I see you...)
https://github.com/madler/zlib/pull/175 (not merged, but no idea about the implications)
https://github.com/madler/zlib/pull/174
https://github.com/madler/zlib/pull/170
https://github.com/madler/zlib/pull/169
https://github.com/madler/zlib/pull/168
https://github.com/madler/zlib/pull/167 (msvc13, msvc15)
https://github.com/madler/zlib/pull/164
https://github.com/madler/zlib/pull/163
https://github.com/madler/zlib/pull/161 (msvc, not sure if relevant)
https://github.com/madler/zlib/pull/159
https://github.com/madler/zlib/pull/156
https://github.com/madler/zlib/pull/153
https://github.com/madler/zlib/pull/152
https://github.com/madler/zlib/pull/150
https://github.com/madler/zlib/pull/148
https://github.com/madler/zlib/pull/145
https://github.com/madler/zlib/pull/139
https://github.com/madler/zlib/pull/138
https://github.com/madler/zlib/pull/134
https://github.com/madler/zlib/pull/132
https://github.com/madler/zlib/pull/129
https://github.com/madler/zlib/pull/127 (msvc15)
https://github.com/madler/zlib/pull/126
https://github.com/madler/zlib/pull/125
https://github.com/madler/zlib/pull/120
https://github.com/madler/zlib/pull/118
https://github.com/madler/zlib/pull/116
https://github.com/madler/zlib/pull/115
https://github.com/madler/zlib/pull/113
https://github.com/madler/zlib/pull/106 (msvc15)
https://github.com/madler/zlib/pull/103
https://github.com/madler/zlib/pull/97
https://github.com/madler/zlib/pull/96
https://github.com/madler/zlib/pull/92 (msvc12, msvc14)
https://github.com/madler/zlib/pull/91
https://github.com/madler/zlib/pull/83
https://github.com/madler/zlib/pull/77
https://github.com/madler/zlib/pull/74
https://github.com/madler/zlib/pull/73
https://github.com/madler/zlib/pull/72
https://github.com/madler/zlib/pull/71 (msvc13)
https://github.com/madler/zlib/pull/68
https://github.com/madler/zlib/pull/66
https://github.com/madler/zlib/pull/65
https://github.com/madler/zlib/pull/59 (oops, merged by you)
https://github.com/madler/zlib/pull/55
https://github.com/madler/zlib/pull/52
https://github.com/madler/zlib/pull/43

**Comment by tbeu** [comment]
You can remove madler/zlib#261 from that list.

**Comment by mtl1979** [comment]
Posting lists like this is waste of our resources... We constantly follow the discussion on madler/zlib and apply fixes that are suggested or figure out ourselves how to fix the issue.
