### ISSUE TITLE
madler/zlib issues and others: Are these fixed?

### ISSUE THREAD

**Issue by timofonic** [Dead2/zlib-ng#119]
Hello.

Sorry, another boring list. This one is about the issues found in maddle/zlib plus references to bugs in other software.

https://github.com/madler/zlib/issues/297
https://github.com/madler/zlib/issues/296
https://github.com/madler/zlib/issues/294
https://github.com/madler/zlib/issues/293
https://github.com/madler/zlib/issues/289
https://github.com/madler/zlib/issues/287
https://github.com/madler/zlib/issues/280
https://github.com/madler/zlib/issues/276
https://github.com/madler/zlib/issues/275
https://github.com/madler/zlib/issues/274
https://github.com/madler/zlib/issues/273
https://github.com/madler/zlib/issues/268
https://github.com/madler/zlib/issues/266
https://github.com/madler/zlib/issues/259
https://github.com/madler/zlib/issues/258
https://github.com/madler/zlib/issues/254
https://github.com/madler/zlib/issues/253
https://github.com/madler/zlib/issues/250
https://github.com/madler/zlib/issues/246
https://github.com/madler/zlib/issues/238
https://github.com/madler/zlib/issues/231
https://github.com/madler/zlib/issues/221
https://github.com/madler/zlib/issues/218
https://github.com/madler/zlib/issues/217
https://github.com/madler/zlib/issues/216
https://github.com/madler/zlib/issues/205
https://github.com/madler/zlib/issues/200 (https://github.com/madler/zlib/issues/249 is duplicated of this)
https://github.com/madler/zlib/issues/199
https://github.com/madler/zlib/issues/192
https://github.com/madler/zlib/issues/188
https://github.com/madler/zlib/issues/180
https://github.com/madler/zlib/issues/162
https://github.com/madler/zlib/issues/147
https://github.com/madler/zlib/issues/143
https://github.com/madler/zlib/issues/137
https://github.com/madler/zlib/issues/133
https://github.com/madler/zlib/issues/104 (you replied there, what happened on this?)
https://github.com/madler/zlib/issues/87 (you replied and @madler said "I support the idea of a group of dedicated people to maintain zlib.". What happened?)
https://github.com/madler/zlib/issues/78
https://github.com/madler/zlib/issues/62 (I guess this is irrelevant)
https://github.com/madler/zlib/issues/49
https://github.com/madler/zlib/issues/41

## References from others

https://github.com/mumble-voip/mumble-releng/commit/3dcee9372daff97323f9b8614bd335e30e58ab7a
https://reviews.freebsd.org/D3344
https://github.com/maitrihegde/tortoisesvn/commit/ada5c413e53ed59e7011a5257479ca4a758c71f1
https://github.com/luanzhiye/tortoisesvn/commit/c9017c68c9a7fe5a83c20113dabe1048d3b18ef9
https://github.com/svn2github/tortoisesvn/commit/0a61eec7e37e0677b0108ae9d0c43f000a748e63
https://github.com/maitrihegde/tortoisesvn/commit/212b25c9a0cd03c90782802250e0e78edcef8aea
https://github.com/TomDataworks/3p-zlib/commit/e31a0d5c7911921363277d3f973faa09c81ff818
https://github.com/tannerhelland/zlib/commit/bfa8e1bccbc0ac5f0711cbc119655effe74014b7
https://github.com/ngyuki/php-src/commit/8d41f6dab66167ed1f888a4c8c66390033eda155
https://github.com/coapp-packages/zlib/issues/5
https://github.com/jpd002/Play-/issues/11
https://github.com/jpd002/Play-/issues/483

Thanks a lot for your great efforts and your patience. I think this should be made an organization and form a team, zlib is very widely used and deserves it. Do you know if there's interest about this? madler was interested on it.

Kind regards.

**Comment by mtl1979** [comment]
win32/Makefile.gcc was integrated to main Makefile.in so maintaining all supported platforms would be as easy as possible. We have integrated a lot of fixes from issues in zlib project but some are currently low priority as we are trying to freeze the codebase so we can fix some big issues introduced by various third-party optimizations before making first stable version. We also need to implement proper test framework so we can catch potential issues as early as possible.
