### ISSUE TITLE
Forks: Unforking? Any interesting stuff? Would they use zlib-ng instead forking themselves and collaborate?

### ISSUE THREAD

**Issue by timofonic** [Dead2/zlib-ng#120]
What about zlib forks I found? What about those libz forks?  Any interesting stuff?
What about unforking? Would they use zlib-ng instead forking themselves and collaborate in a common project?

What about a future official organization? What about forming a team? Even @madler approves it....

## Libz 
https://github.com/freebsd/freebsd/tree/master/lib/libz
https://github.com/openbsd/src/tree/master/lib/libz
https://gitlab.com/sortix/libz

There's [irc://irc.freenode.net/#libz](irc://irc.freenode.net/#libz) too ;)

## Zlib
 https://github.com/NetBSD/pkgsrc/tree/trunk/devel/zlib
 https://github.com/IIJ-NetBSD/netbsd-src/tree/master/lib/libz
 https://github.com/IIJ-NetBSD/netbsd-src/tree/master/common/dist/zlib
 https://github.com/TomDataworks/3p-zlib/
 https://github.com/gildor2/fast_zlib
 https://github.com/php/php-src/tree/master/ext/zlib
 https://github.com/osom8979/tbag/tree/master/external/zlib
 https://github.com/telegramdesktop/zlib
 https://github.com/richgel999/miniz
 https://github.com/marinm/zlib
 https://github.com/abc-mod/abc_external_zlib/
 https://github.com/LineageOS/android_external_zlib
 https://github.com/crdroidandroid/android_external_zlib
 https://github.com/BenzoRoms/external_zlib
 https://github.com/fuchsia-mirror/third_party-zlib
 https://github.com/RenegadeOS/platform_external_zlib
 https://github.com/cloudflare/zlib
 https://github.com/geoff-codes/zlib
 https://github.com/wzv5/libpck/tree/master/zlib
https://sortix.org/libdeflate/
https://gitlab.com/sortix/libdeflate/
http://pkgs.fedoraproject.org/rpms/zlib
https://build.opensuse.org/package/show/devel:libraries:c_c++/zlib
 https://github.com/mtl1979/zlib-ng

**Comment by mtl1979** [comment]
There will always be forks because we can't include every possible code piece in "official" zlib-ng due to license issues and overlapping code. We also need to make sure contributed code doesn't break existing code. We are currently compiling list of platforms and operating systems we should support in first or subsequent official releases and which ones that stock zlib supports we should and can drop in first release.
