### ISSUE TITLE
Archlinux User Repository: zlib-ng-git package orphaned

### ISSUE THREAD

**Issue by timofonic** [Dead2/zlib-ng#122]
Hello.

I saw this package is orphaned. Any volunteer? I'm these days struggingwith hardware problems.

https://aur.archlinux.org/packages/zlib-ng-git/

Kind regards.

**Comment by Dead2** [comment]
Seems they have deleted the package completely. Probably because it conflicts with zlib, this will improve once we merge the renamelib branch. :)
